### ISSUE TITLE
Hardcoded strings in settings and extentions pages

### ISSUE THREAD

**Issue by legofanlovessayori** [Floorp-Projects/Unified-l10n-central#50]
Have made an issue on the main repo in the past about [this](https://github.com/Floorp-Projects/Floorp/issues/555) but it got drowned (?) so ima put it here

The "Preferences" header in about:preferences and the "Extentions" header in about:addons are hardcoded and can't be translated

Screenshots for reference:
![grafik](https://github.com/Floorp-Projects/Unified-l10n-central/assets/94994630/69f8286e-83a5-4c3c-831e-b805eb25e0fb)
![grafik](https://github.com/Floorp-Projects/Unified-l10n-central/assets/94994630/e82ae529-900b-40e7-a1f3-e97f515d318b)

**Comment by CutterKnife** [comment]
According to the dev, this is intentional and not a bug. IDK why.

**Comment by legofanlovessayori** [comment]
🥴

still kinda strange choice to hardcode them

**Comment by legofanlovessayori** [comment]
![grafik](https://github.com/Floorp-Projects/Unified-l10n-central/assets/94994630/c1aa8738-f3f2-40f3-9219-77fb321f6535)
prolly the same story with the "private" label on the firefox account button when in private browsing

**Comment by ioc2e3** [comment]
> 據開發人員稱，這是故意的，而不是錯誤。我不知道為什麼。

... ?

( Preferences header ) and ( Extensions header ) are hardcoded and cannot be translated ...

Don’t understand why did this on purpose ...

.

**Comment by creeper-0910** [comment]
I would like to correct this in the next update.
Do you have any other hardcoded text?

**Comment by legofanlovessayori** [comment]
the support and release notes links on the new tab page + those i mentioned in here

**Comment by creeper-0910** [comment]
OK. I'll try.

**Comment by creeper-0910** [comment]
https://github.com/Floorp-Projects/Floorp/pull/1036
https://github.com/Floorp-Projects/Unified-l10n-central/pull/53
https://github.com/Floorp-Projects/Floorp-core/pull/64
Perhaps this will fix it...

**Comment by surapunoyousei** [comment]
Fixed
