### ISSUE TITLE
Cannot translate new strings

### ISSUE THREAD

**Issue by CutterKnife** [Floorp-Projects/Unified-l10n-central#54]
既にご存知かとは思われますが、記録のために書き残しておきます。

example:
<img width="449" alt="スクリーンショット 2024-04-04 16 35 17" src="https://github.com/Floorp-Projects/Unified-l10n-central/assets/110194318/8354250a-8952-412d-bf2f-59df5a681189">
<img width="297" alt="スクリーンショット 2024-04-04 16 35 57" src="https://github.com/Floorp-Projects/Unified-l10n-central/assets/110194318/659f6d60-3e97-44eb-a231-a97ee87e852a">

**Comment by creeper-0910** [comment]
あら、修正しておきますね(*`･ω･)ゞ

**Comment by CutterKnife** [comment]
こちら側で確認できた文字列のリストも残しておきます (すべてではないかもしれません):
- Enable padding at the top (設定 > デザイン)
- Toggle User Interface (設定 > CSK)
- Change Zoom Level, Zoom In, Zoom Out, Reset Zoom (BMS)

**Comment by surapunoyousei** [comment]
全部解決してるねこれ
